# Generated by Django 4.1.5 on 2023-02-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_shop', '0002_wishitemshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitemshop',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
